version: '3'

services:
  api-server:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - api-data:/code/data
      - ./out:/code/out
    networks:
      - lost
    depends_on:
      - mongodb
      - postgres

  frontend:
    build: ./client
    ports:
      - 80:80
    volumes:
      - ./client:/src
    networks:
      - lost
    environment:
      - PORT=80
      - PUBLIC_API_URL=http://eivarin.xyz:8000
      # - PUBLIC_API_URL=http://localhost:8000
      - PRIVATE_API_URL=http://api-server:8000
    depends_on:
      - api-server

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - lost

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lost
    environment:
      - POSTGRES_DB=acordaos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  api-data:
  mongo-data:
  postgres-data:

networks:
  lost:
    driver: bridge